version: 2.1
jobs:
  analytics-core-build:
    machine:
      image: ubuntu-2004:202008-01
    steps:
    - checkout
    - restore_cache:
        key: dp-dependency-cache-{{ checksum "pom.xml" }}
    - run:
        name: sunbird-analytics-core-build
        command: |
          update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java 2
          export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH
          echo $(java -version)
          echo $JAVA_HOME
          echo $PATH
          echo $(update-java-alternatives -l)
          mvn scoverage:report
    - save_cache:
        key: dp-dependency-cache-{{ checksum "pom.xml" }}
        paths: ~/.m2
    - save_cache:
        key: dp-core-libraries
        paths:
          - analytics-core/target/analytics-core-2.0.jar
          - analytics-job-driver/target/analytics-job-driver-2.0.jar
    - run:
        name: sonar
        command: |
          export JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64
          mvn -X sonar:sonar -Dsonar.projectKey=project-sunbird_sunbird-analytics-core -Dsonar.organization=project-sunbird -Dsonar.exclusions=analytics-core/src/main/scala/org/ekstep/analytics/streaming/** -Dsonar.host.url=https://sonarcloud.io -Dsonar.scala.coverage.reportPaths=/home/circleci/project/target/scoverage.xml

workflows:
  version: 2.1
  workflow:
    jobs:
    - analytics-core-build
